name = "ns1" # todo
main = "js/_worker.js"
compatibility_date = "2024-05-26"


[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true


[[routes]]
pattern = "bugwildcard.cloudproxyip.my.id.sakera.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "bugwildcard.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "sublink.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "sublink.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "sakera.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.sakera.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.sakera.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.sakera.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.sakera.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.sakera.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.sakera.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.sakera.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.sakera.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.sakera.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.sakera.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.sakera.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.sakera.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.sakera.cloudproxyip.my.id"
custom_domain = true

