name = "ns1" # todo
main = "js/_worker.js"
compatibility_date = "2024-05-26"


[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true


[[routes]]
pattern = "user.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "woless.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.woless.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.woless.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.woless.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.woless.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.woless.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.woless.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.woless.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.woless.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.woless.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.woless.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.woless.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.woless.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.woless.kere.us.kg"
custom_domain = true

