name: Replace Subdomain Weekly

on:
  schedule:
  - cron: '0 0 * * 0' # Jalankan setiap minggu pada pukul 00:00 UTC pada hari Minggu
  workflow_dispatch:

jobs:
  replace-subdomain:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml

    - name: Run Python script to replace subdomain
      run: python replace_subdomain.py

    - name: Display updated wrangler.toml
      run: |
        echo "Displaying wrangler.toml content after update:"
        cat wrangler.toml

    - name: Display updated _worker.js
      run: |
        echo "Displaying _worker.js content after update:"
        cat _worker.js

    - name: Check if files are updated
      run: |
        echo "Checking if 'ns1.cepu.us.kg' is removed from wrangler.toml and _worker.js"
        if ! grep -q "ns1.cepu.us.kg" wrangler.toml; then
          echo "wrangler.toml updated successfully"
        else
          echo "wrangler.toml not updated"
        fi
        if ! grep -q "ns1.cepu.us.kg" _worker.js; then
          echo "_worker.js updated successfully"
        else
          echo "_worker.js not updated"
        fi

    - name: Commit changes to wrangler.toml and _worker.js
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add wrangler.toml _worker.js subdomain.yml
        git commit -m "Update subdomain"
        git push
