name: Proxy Scanner

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  scanner:
    runs-on: ubuntu-latest
    concurrency:
      group: proxy-scan

    steps:
      - uses: actions/checkout@v3
      - name: Use Bun
        uses: oven-sh/setup-bun@v2
      - name: Start Scan
        run: |
          bun install && bun run ./helper/proxyip.ts
      - name: Commit changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add proxyList.txt kvProxyList.json
          git commit -m "Update proxy list"
          git push
      - name: Publish Result
        if: ${{ success() }}
        uses: EndBug/add-and-commit@v9
        with:
          add: '["proxyList.txt", "kvProxyList.json"]'
          default_author: github_actions
          fetch: false
          tag_push: "--force"
          message: "Update proxy list"
